name: 'CI/CD'

on:
  - push
  - workflow_dispatch

jobs:
  build:
    name: 'CI: Restore, Build & Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup DynamoDB Local
        run: |
          docker run -d -p 8000:8000 amazon/dynamodb-local
      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Lint
        run: dotnet format --verify-no-changes --no-restore
      - name: Test
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test/OpenIddict.AmazonDynamoDB.Tests/TestResults/coverage.info
          fail_ci_if_error: false

  publish:
    name: 'CD: Pack & Publish'
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x

      - name: Pack
        run: |
          dotnet pack

      - name: Publish
        run: |
          dotnet nuget push **\*.nupkg \
            --source 'https://api.nuget.org/v3/index.json' \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate
