name: 'CI: Restore, Build & Test'

on:
  - push
  - workflow_dispatch

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: '*'
      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
      - name: Restore
        run: |
          dotnet restore
      - name: Build
        run: |
          dotnet build --no-restore
      - name: Test
        run: |
          dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/src/GraphQL.EntityFrameworkCore.Helpers.Tests/TestResults/coverage.net6.0.info
          fail_ci_if_error: false
